// Generated by Wrangler
// After adding bindings to `wrangler.json`, regenerate this interface via `npm run cf-typegen`
interface Env {
    JWT_SECRET :string;
    DIRECT_DATABASE_URL :string;
    DATABASE_URL : string;
}
